[server]
headless = true
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

# Membuka izin embedding iframe untuk semua domain / domain blog
[global]
developmentMode = false
